apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-manager
  name: task-manager
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
      nodePort: 30000
  selector:
    app: task-manager
  type: NodePort
