apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-manager
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: denislav1396/task-manager:latest
          imagePullPolicy: Always
          name: task-manager
          ports:
            - name: http-port
              containerPort: 8081
          envFrom:
            - secretRef:
                name: task-manager-config
          resources:
            limits:
              cpu: 250m
              memory: 400Mi
            requests:
              cpu: 250m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            privileged: false
            readOnlyRootFilesystem: true
